spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: oauth-service
          uri: lb://oauth-service
          predicates:
            - Path=/api/security/**
          filters:
            - StripPrefix=2
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/v1/user-service/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/v1/product-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: product-service
                fallbackUri: forward:/productServiceFallback
            - AuthenticationFilter
        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/v1/reservation-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: reservation-service
                fallbackUri: forward:/reservationServiceFallback
            - AuthenticationFilter
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/v1/payment-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: payment-service
                fallbackUri: forward:/paymentServiceFallback
        - id: credit-card-processor-service
          uri: lb://credit-card-processor-service
          predicates:
            - Path=/v1/credit-card/**
          filters:
            - name: CircuitBreaker
              args:
                name: credit-card-processor-service
                fallbackUri: forward:/creditCardProcessorServiceFallback
        - id: orders-service
          uri: lb://orders-service
          predicates:
            - Path=/v1/orders-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: orders-service
                fallbackUri: forward:/ordersServiceFallback

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${server.port}

# Health check
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    enabled: true
    urls:
      - name: api-gateway
        url: /v3/api-docs
      - name: product-service
        url: /aggregate/product-service/v3/api-docs
      - name: reservation-service
        url: /aggregate/reservation-service/v3/api-docs
      - name: payment-service
        url: /aggregate/payment-service/v3/api-docs
      - name: credit-card-processor-service
        url: /aggregate/credit-card-processor-service/v3/api-docs
      - name: orders-service
        url: /aggregate/orders-service/v3/api-docs

  api-docs:
    enabled: true
    path: /v3/api-docs
